import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { log } from '../core/logger.js';

/**
 * Parse Cargo.lock into dependency list.
 * Cargo.lock uses TOML with [[package]] sections — same pattern as poetry.lock.
 */
export function parseLockfile(filePath) {
  let content;
  try { content = readFileSync(filePath, 'utf8'); }
  catch (err) { throw new Error(`cannot read ${filePath}: ${err.code || err.message}`); }

  const generatedHeader = /^# This file is automatically @generated by Cargo\.$/m.test(content);
  const versionHeader = /^version\s*=\s*\d+\s*$/m.test(content);
  if (!generatedHeader && !versionHeader) {
    throw new Error(`invalid Cargo.lock schema in ${filePath}: Cargo header/version is missing`);
  }

  const deps = [];
  let current = null;
  let unresolvedEntries = 0;

  const flush = () => {
    if (!current) return;
    if (!pushRegistryPackage(current, deps)) unresolvedEntries++;
  };

  for (const line of content.split('\n')) {
    const trimmed = line.trim();

    if (trimmed === '[[package]]') {
      flush();
      current = {};
      continue;
    }

    if (current) {
      const m = trimmed.match(/^(name|version|source)\s*=\s*"(.+?)"/);
      if (m) current[m[1]] = m[2];
    }
  }

  // Last entry
  flush();

  log.debug(`parsed ${deps.length} deps from ${filePath}`);
  attachParserStatus(deps, unresolvedEntries);
  return deps;
}

function pushRegistryPackage(current, deps) {
  if (!current?.name || !current?.version) return false;
  const source = String(current.source || '');
  const cratesIo = source === 'registry+https://github.com/rust-lang/crates.io-index' ||
    source === 'sparse+https://index.crates.io/';
  // Workspace/path packages have no registry source; git packages have a git
  // source. Neither is a crates.io component and must not be queried as one.
  if (!cratesIo) return false;
  deps.push({
    name: current.name,
    version: current.version,
    ecosystem: 'cargo',
    isDirect: false,
    isPinned: true,
    sourceType: 'registry',
    source,
  });
  return true;
}

function attachParserStatus(deps, unresolvedEntries) {
  Object.defineProperty(deps, 'unresolvedEntries', {
    enumerable: false,
    value: unresolvedEntries,
  });
}

/**
 * Discover Cargo dependency files in a directory.
 */
export function discover(dir) {
  const lockfiles = [];
  const manifests = [];

  const lockPath = join(dir, 'Cargo.lock');
  const tomlPath = join(dir, 'Cargo.toml');

  if (existsSync(lockPath)) lockfiles.push(lockPath);
  if (existsSync(tomlPath)) manifests.push(tomlPath);

  return { lockfiles, manifests };
}
