/**
 * Recorder shim + harness for the dynamic sandbox.
 *
 * The sandbox primitive (`./index.js`) enforces isolation; the harness makes
 * that isolation observable. We generate a small Node recorder shim (pure
 * `node:` builtins) that monkey-patches the loaded module objects so candidate
 * package code logs every process spawn, network attempt, and filesystem
 * write as JSONL into an evidence file inside the workdir. The shim is injected
 * via argv `--require` — NOT NODE_OPTIONS — so child processes spawned by the
 * candidate don't double-instrument.
 *
 * Trust boundaries (same rules as the rest of vexes):
 *  - The candidate runs ONLY in the OS isolation primitive, and only when the
 *    caller explicitly passes `allow: true` (analyze --sandbox / inspect
 *    --sandbox do this; the module refuses otherwise).
 *  - Evidence is classified *in the sandbox* against the workdir + OS temp:
 *    writes to either are normal package hygiene, writes anywhere else are
 *    `outside: true` — the signal that later becomes SANDBOX_BEHAVIOR.
 *  - The evidence file is read back by the host after the run; the workdir is
 *    the caller's throwaway.
 *
 * @module analysis/sandbox/harness
 */

import { join } from 'node:path';
import { readFileSync, writeFileSync, existsSync, statSync, realpathSync } from 'node:fs';
import { runSandboxed } from './index.js';
import { SIGNAL_CONFIDENCE } from '../signals.js';

const DEFAULT_TIMEOUT_MS = 10000;

/**
 * Build the recorder shim source string (pure — no side effects).
 * The generated file is a CommonJS module safe to load with
 * `node --require <path> <entry>`.
 *
 * @param {object} opts
 * @param {string} opts.evidencePath — absolute path to the JSONL evidence file
 * @param {string} opts.workdir — absolute path whose writes are "inside"
 * @returns {string} shim source
 */
export function buildRecorderShim({ evidencePath, workdir }) {
  const ev = JSON.stringify(String(evidencePath));
  // Resolve WROOT to its real path up front: inside the sandbox, process.cwd()
  // reports the resolved (/private/...) form, so a WROOT built from the
  // caller's symlinked (/var/folders/...) tempdir would never match the
  // sandbox cwd and every relative "inside" write would classify as outside.
  let realWd;
  try { realWd = realpathSync(String(workdir)); } catch { realWd = String(workdir); }
  const wr = JSON.stringify(realWd);
  return [
    "'use strict';",
    '// Generated by vexes sandbox harness (analysis/sandbox/harness.js).',
    '// Records dynamic behavior into a JSONL evidence file. Only node: builtins.',
    'const fs = require(\'node:fs\');',
    'const os = require(\'node:os\');',
    'const path = require(\'node:path\');',
    'const cp = require(\'node:child_process\');',
    'const net = require(\'node:net\');',
    'const http = require(\'node:http\');',
    'const https = require(\'node:https\');',
    'const dgram = require(\'node:dgram\');',
    '',
    `const EVIDENCE = ${ev};`,
    `const WROOT = path.resolve(${wr});`,
    '',
    '// Evidence writer uses openSync/writeSync (NOT the writeFile*/appendFile*',
    '// family we patch below). Binding appendFileSync to the fs module would',
    '// re-enter a patched method via Node\'s internal this.writeFileSync',
    '// delegation and self-recurses; openSync/writeSync are not patched, so',
    '// recording can never loop back through itself.',
    'let _recFd = -1;',
    'function classify(target) {',
    '  if (typeof target !== \'string\') return false;',
    '  let abs;',
    '  try { abs = path.resolve(target); } catch { return false; }',
    '  const inside = (base) => abs === base || abs.startsWith(base + path.sep);',
    '  if (inside(WROOT)) return false;',
    '  const tmp = os.tmpdir();',
    '  if (tmp && inside(tmp)) return false;',
    '  return true;',
    '}',
    '',
    'function rec(line) {',
    '  try {',
    '    if (_recFd === -1) _recFd = fs.openSync(EVIDENCE, \'a\');',
    '    fs.writeSync(_recFd, JSON.stringify(line) + \'\\n\');',
    '  } catch { /* evidence unavailable — drop, never crash the candidate */ }',
    '}',
    '',
    'function hint() {',
    '  try {',
    '    const frames = ((new Error(\'hint\')).stack || \'\').split(\'\\n\').slice(1).filter(Boolean);',
    '    const own = frames.filter((f) => f.includes(\'.vexes-recorder.cjs\'));',
    '    const offset = own.length ? frames.indexOf(own[own.length - 1]) + 1 : 1;',
    '    return String(frames[offset] || \'\').trim().slice(0, 200);',
    '  } catch { return \'\'; }',
    '}',
    '',
    '// child_process: record every spawn/exec/fork, then delegate to the original',
    'const _cp = {',
    '  spawn: cp.spawn, spawnSync: cp.spawnSync,',
    '  exec: cp.exec, execSync: cp.execSync,',
    '  execFile: cp.execFile, execFileSync: cp.execFileSync,',
    '  fork: cp.fork,',
    '};',
    'const spawnHit = (cmd, args) => ({ t: \'spawn\', file: String(cmd), args: Array.isArray(args) ? args.map((a) => String(a)).slice(0, 20) : [], at: hint() });',
    'const execHit = (cmd) => ({ t: \'spawn\', file: \'exec\', command: String(cmd).slice(0, 200), at: hint() });',
    'cp.spawn = function (cmd, args) { rec(spawnHit(cmd, args)); return _cp.spawn.apply(this, arguments); };',
    'cp.spawnSync = function (cmd, args) { rec(spawnHit(cmd, args)); return _cp.spawnSync.apply(this, arguments); };',
    'cp.exec = function (cmd) { rec(execHit(cmd)); return _cp.exec.apply(this, arguments); };',
    'cp.execSync = function (cmd) { rec(execHit(cmd)); return _cp.execSync.apply(this, arguments); };',
    'cp.execFile = function (cmd, args) { rec(spawnHit(cmd, args)); return _cp.execFile.apply(this, arguments); };',
    'cp.execFileSync = function (cmd, args) { rec(spawnHit(cmd, args)); return _cp.execFileSync.apply(this, arguments); };',
    'cp.fork = function (mod) { rec({ t: \'spawn\', file: \'fork\', args: [String(mod)], at: hint() }); return _cp.fork.apply(this, arguments); };',
    '',
    '// net: connect (tcp/unix) + http(s) request/get + dgram send',
    'const _socketConnect = net.Socket.prototype.connect;',
    'net.Socket.prototype.connect = function (a, b) {',
    '  rec({ t: \'network\', type: \'net.connect\', ...targetOf(a, b), at: hint() });',
    '  return _socketConnect.apply(this, arguments);',
    '};',
    'const targetOf = (a, b) => {',
    '  if (Array.isArray(a)) a = a[0]; // Node 26 wraps normalized args in an array',
    '  if (Array.isArray(b)) b = b[0];',
    '  if (typeof a === \'string\') return { host: a, port: null };',
    '  if (a && typeof a === \'object\') return { host: String(a.hostname || a.host || \'object\'), port: a.port != null ? a.port : null };',
    '  if (b && typeof b === \'object\') return { host: String(b.hostname || b.host || \'object\'), port: b.port != null ? b.port : null };',
    '  return { host: \'unknown\', port: null };',
    '};',
    'const markHttp = (a, b) => { const t = targetOf(a, b); rec({ t: \'network\', ...t, at: hint() }); };',
    'const _http = { request: http.request, get: http.get };',
    'http.request = function (a, b) { markHttp(a, b); return _http.request.apply(this, arguments); };',
    'http.get = function (a, b) { markHttp(a, b); return _http.get.apply(this, arguments); };',
    'const _https = { request: https.request, get: https.get };',
    'https.request = function (a, b) { markHttp(a, b); return _https.request.apply(this, arguments); };',
    'https.get = function (a, b) { markHttp(a, b); return _https.get.apply(this, arguments); };',
    'const _dgramSend = dgram.Socket.prototype.send;',
    'dgram.Socket.prototype.send = function (buf, port, host) { rec({ t: \'network\', type: \'dgram.send\', host: typeof host === \'string\' ? host : null, port: typeof port === \'number\' ? port : null, at: hint() }); return _dgramSend.apply(this, arguments); };',
    '',
    '// fs writes (string targets only; fd-number writes are streamed from an',
    '// already-recorded open and skipped)',
    'const _fs = {',
    '  writeFile: fs.writeFile, writeFileSync: fs.writeFileSync,',
    '  appendFile: fs.appendFile, appendFileSync: fs.appendFileSync,',
    '  createWriteStream: fs.createWriteStream,',
    '};',
    'const writeHit = (p, fn) => ({ t: \'write\', fn, path: String(p), outside: classify(p), at: hint() });',
    'fs.writeFile = function (p) { if (typeof p === \'string\') rec(writeHit(p, \'writeFile\')); return _fs.writeFile.apply(this, arguments); };',
    'fs.writeFileSync = function (p) { if (typeof p === \'string\') rec(writeHit(p, \'writeFileSync\')); return _fs.writeFileSync.apply(this, arguments); };',
    'fs.appendFile = function (p) { if (typeof p === \'string\') rec(writeHit(p, \'appendFile\')); return _fs.appendFile.apply(this, arguments); };',
    'fs.appendFileSync = function (p) { if (typeof p === \'string\') rec(writeHit(p, \'appendFileSync\')); return _fs.appendFileSync.apply(this, arguments); };',
    'fs.createWriteStream = function (p) { if (typeof p === \'string\') rec(writeHit(p, \'createWriteStream\')); return _fs.createWriteStream.apply(this, arguments); };',
    '',
    '// cwd changes — cheap "am I poking around" signal',
    'const _cwd = process.cwd, _chdir = process.chdir;',
    'process.cwd = function () { rec({ t: \'cwd\', at: hint() }); return _cwd.call(process); };',
    'process.chdir = function (d) { rec({ t: \'chdir\', dir: String(d), at: hint() }); return _chdir.apply(process, arguments); };',
    '',
    'module.exports = {};',
  ].join('\n');
}

/**
 * Build the argv to run an entry under the recorder shim. `--require` (argv),
 * not NODE_OPTIONS, so child processes spawned by the candidate do not inherit
 * the instrumentation and double-record.
 * @param {object} opts
 * @param {string} opts.shimPath — where buildRecorderShim's output was written
 * @param {string} opts.entryScript — absolute path to the candidate's entry file
 * @returns {string[]}
 */
export function buildHarnessCommand({ shimPath, entryScript }) {
  return ['node', '--require', shimPath, entryScript];
}

/**
 * Parse raw JSONL evidence text into structured buckets. Garbage lines are
 * skipped (a corrupt/truncated evidence file must never abort analysis).
 * `workdir` is accepted for signature stability; the outside/inside split is
 * already decided by the shim at record time and re-verified nowhere else.
 *
 * @param {string} text — JSONL evidence file contents
 * @param {string} [_workdir] — accepted for API stability
 * @returns {{ spawns: Array, networkAttempts: Array, outsideWrites: Array, otherWrites: Array, cwdChanges: Array }}
 */
export function parseEvidence(text, _workdir) {
  const out = { spawns: [], networkAttempts: [], outsideWrites: [], otherWrites: [], cwdChanges: [] };
  for (const raw of String(text || '').split('\n')) {
    const line = raw.trim();
    if (!line) continue;
    let e;
    try { e = JSON.parse(line); } catch { continue; } // garbage/truncated line
    const at = e.at;
    switch (e.t) {
      case 'spawn': out.spawns.push({ cmd: e.command || e.file, file: e.file, args: e.args || [], at }); break;
      case 'network': out.networkAttempts.push({ type: e.type, host: e.host, port: e.port, at }); break;
      case 'write': (e.outside ? out.outsideWrites : out.otherWrites).push({ path: e.path, fn: e.fn, at }); break;
      case 'cwd': case 'chdir': out.cwdChanges.push({ dir: e.dir, at }); break;
      default: break;
    }
  }
  return out;
}

/** Read an evidence file from disk (missing/corrupt ⇒ empty buckets, no throw). */
export function readEvidenceFile(evidencePath, workdir) {
  try { return parseEvidence(readFileSync(evidencePath, 'utf8'), workdir); }
  catch { return parseEvidence('', workdir); }
}

/**
 * Pick the entry script for a package extracted into `dir`:
 * package.json bin (string or first bin entry) → main → index.js.
 * Falls back to index.js when package.json is absent. Returns null if none of
 * the candidates exist on disk. Shared by analyze --sandbox and
 * inspect --sandbox so entry selection can't drift.
 */
export function pickEntryScript(dir) {
  let pkg = {};
  try { pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')); } catch { /* no manifest */ }
  const candidates = [];
  if (typeof pkg.bin === 'string') candidates.push(pkg.bin);
  else if (pkg.bin && typeof pkg.bin === 'object') candidates.push(...Object.values(pkg.bin).filter(v => typeof v === 'string'));
  else if (typeof pkg.main === 'string') candidates.push(pkg.main);
  if (typeof pkg.main === 'string' && !candidates.includes(pkg.main)) candidates.push(pkg.main);
  candidates.push('index.js');
  for (const c of candidates) {
    const cleaned = String(c).replace(/^\.\//, '');
    // The manifest is untrusted: refuse entry paths that could step back out
    // of the throwaway workdir (.. segments, absolute, drive escapes).
    if (!cleaned || cleaned.startsWith('/') || /^[A-Za-z]:[\\/]/.test(cleaned) || cleaned.split(/[/\\]+/).includes('..')) continue;
    const p = join(dir, cleaned);
    if (existsSync(p) && statSync(p).isFile()) return p;
  }
  return null;
}

/**
 * Turn parsed evidence into a SANDBOX_BEHAVIOR signal, or null when nothing
 * was recorded. Severity: outside writes are CRITICAL; spawns/network are
 * HIGH; anything else that slipped through is MODERATE. Evidence is capped so
 * the JSON contract doesn't balloon.
 */
export function buildSandboxSignal({ name, version, evidence }) {
  const ev = evidence || {};
  const outsideWrites = ev.outsideWrites || [];
  const spawns = ev.spawns || [];
  const network = ev.networkAttempts || [];
  if (outsideWrites.length === 0 && spawns.length === 0 && network.length === 0) return null;
  const severity = outsideWrites.length > 0 ? 'CRITICAL' : (spawns.length > 0 || network.length > 0 ? 'HIGH' : 'MODERATE');
  const behavior = [];
  if (outsideWrites.length) behavior.push(`${outsideWrites.length} outside write${outsideWrites.length === 1 ? '' : 's'}`);
  if (spawns.length) behavior.push(`${spawns.length} process spawn${spawns.length === 1 ? '' : 's'}`);
  if (network.length) behavior.push(`${network.length} network attempt${network.length === 1 ? '' : 's'}`);
  return {
    signal: 'SANDBOX_BEHAVIOR',
    severity,
    confidence: SIGNAL_CONFIDENCE.SANDBOX_BEHAVIOR,
    description: `sandboxed execution of ${name}@${version} recorded: ${behavior.join(', ')}`,
    evidence: {
      dynamic: {
        spawns: spawns.slice(0, 25),
        networkAttempts: network.slice(0, 25),
        outsideWrites: outsideWrites.slice(0, 25),
      },
    },
    layer: 3,
  };
}

/**
 * Run an extracted package entry inside the OS sandbox under the recorder
 * shim and read back the behavioral evidence. REFUSES by default; a missing
 * isolation host or allow=false returns { status: 'refused' } (see
 * index.js runSandboxed). The workdir is the caller's throwaway — it contains
 * both the extracted package and the shim/evidence files.
 *
 * @param {object} opts
 * @param {string} opts.workdir — mkdtemp dir with extracted package
 * @param {string} opts.entryScript — absolute entry (see pickEntryScript)
 * @param {string} [opts.shimSource] — override recorder source (tests)
 * @param {boolean} [opts.allow=false] — must be true to actually spawn
 * @param {number} [opts.timeoutMs=DEFAULT_TIMEOUT_MS]
 * @param {object} [opts.host] — same override convention as runSandboxed
 * @returns {object} runSandboxed result + { evidence }
 */
export function runHarnessed(opts = {}) {
  const { workdir, entryScript, shimSource, allow = false, timeoutMs = DEFAULT_TIMEOUT_MS } = opts;
  const evPath = join(workdir, '.vexes-evidence.jsonl');
  const shimPath = join(workdir, '.vexes-recorder.cjs');
  const source = shimSource || buildRecorderShim({ evidencePath: evPath, workdir });
  writeFileSync(shimPath, source);
  const child = runSandboxed({
    command: buildHarnessCommand({ shimPath, entryScript }),
    workdir,
    allow,
    timeoutMs,
    host: opts.host, // undefined ⇒ detect; null ⇒ forced refusal
  });
  const evidence = readEvidenceFile(evPath, workdir);
  return { ...child, evidence };
}
